-- ============================================================================
-- ANTONELLO PRODUCE PALLET TRACKER DATABASE SETUP SCRIPT
-- This script drops any existing tables and recreates the tables,
-- helper functions, Row Level Security (RLS) policies, and whitelist check.
-- Run this query in your Supabase SQL Editor.
-- ============================================================================

-- 1. DROP EXISTING DATABASE OBJECTS (CASCADE ensures dependent policies are also removed)
DROP TABLE IF EXISTS movements CASCADE;
DROP TABLE IF EXISTS staff CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS allowed_users CASCADE;
DROP FUNCTION IF EXISTS is_whitelisted CASCADE;
DROP FUNCTION IF EXISTS is_admin CASCADE;

-- 2. CREATE TABLES

-- A. Email Whitelist Table
CREATE TABLE allowed_users (
  email TEXT PRIMARY KEY,
  is_admin BOOLEAN DEFAULT FALSE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- B. Staff Roster Table
CREATE TABLE staff (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- C. Customer Directory Table
CREATE TABLE customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  email TEXT NULL,
  phone TEXT NULL,
  contact_person TEXT NULL,
  address TEXT NULL,
  notes TEXT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  status TEXT DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')) NOT NULL
);

-- D. Pallet Movements Ledger Table
CREATE TABLE movements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE NOT NULL,
  recorded_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  edited_at TIMESTAMPTZ NULL,
  customer_id BIGINT REFERENCES customers(id) ON DELETE RESTRICT NOT NULL,
  type TEXT CHECK (type IN ('issue', 'return')) NOT NULL,
  qty INTEGER CHECK (qty > 0) NOT NULL,
  staff TEXT NOT NULL,
  note TEXT NULL
);

-- Trigger for staff name update in movements table
CREATE OR REPLACE FUNCTION update_movements_staff_name()
RETURNS TRIGGER AS $$
BEGIN
  IF OLD.name <> NEW.name THEN
    UPDATE movements SET staff = NEW.name WHERE staff = OLD.name;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_staff_name_update
AFTER UPDATE OF name ON staff
FOR EACH ROW
EXECUTE FUNCTION update_movements_staff_name();


-- 3. CREATE SECURITY HELPER FUNCTION
-- This function runs with security definer (owner privileges) to read from
-- the allowed_users table, checking if the authenticated user's JWT email is whitelisted.
CREATE OR REPLACE FUNCTION is_whitelisted()
RETURNS BOOLEAN 
SECURITY DEFINER 
SET search_path = public
AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 
    FROM allowed_users
    WHERE email = LOWER(auth.jwt() ->> 'email')
  );
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION is_admin()
RETURNS BOOLEAN 
SECURITY DEFINER 
SET search_path = public
AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 
    FROM allowed_users
    WHERE email = LOWER(auth.jwt() ->> 'email')
      AND is_admin = TRUE
  );
END;
$$ LANGUAGE plpgsql;

-- 4. ENABLE ROW LEVEL SECURITY (RLS) ON ALL TABLES
ALTER TABLE allowed_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE staff ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE movements ENABLE ROW LEVEL SECURITY;

-- 5. DEFINE ROW LEVEL SECURITY POLICIES

-- Policies for allowed_users
-- Users can check their own whitelist status, and admins can select all
CREATE POLICY "Users can check their own whitelist status or admins can select all" 
ON allowed_users
FOR SELECT 
TO authenticated
USING (email = LOWER(auth.jwt() ->> 'email') OR is_admin());

CREATE POLICY "Admins can insert whitelisted users" 
ON allowed_users FOR INSERT TO authenticated WITH CHECK (is_admin());

CREATE POLICY "Admins can update whitelisted users" 
ON allowed_users FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());

CREATE POLICY "Admins can delete whitelisted users" 
ON allowed_users FOR DELETE TO authenticated USING (is_admin());

-- Policies for staff
CREATE POLICY "Whitelisted users can read staff roster" 
ON staff FOR SELECT TO authenticated USING (is_whitelisted());

CREATE POLICY "Whitelisted users can insert staff members" 
ON staff FOR INSERT TO authenticated WITH CHECK (is_whitelisted());

CREATE POLICY "Whitelisted users can update staff members" 
ON staff FOR UPDATE TO authenticated USING (is_whitelisted()) WITH CHECK (is_whitelisted());

CREATE POLICY "Whitelisted users can delete staff members" 
ON staff FOR DELETE TO authenticated USING (is_whitelisted());

-- Policies for customers
CREATE POLICY "Whitelisted users can read customer directory" 
ON customers FOR SELECT TO authenticated USING (is_whitelisted());

CREATE POLICY "Whitelisted users can insert new customers" 
ON customers FOR INSERT TO authenticated WITH CHECK (is_whitelisted());

CREATE POLICY "Whitelisted users can update customers" 
ON customers FOR UPDATE TO authenticated USING (is_whitelisted()) WITH CHECK (is_whitelisted());

CREATE POLICY "Whitelisted users can delete customers" 
ON customers FOR DELETE TO authenticated USING (is_whitelisted());

-- Policies for movements
CREATE POLICY "Whitelisted users can read movements" 
ON movements FOR SELECT TO authenticated USING (is_whitelisted());

CREATE POLICY "Whitelisted users can insert movements" 
ON movements FOR INSERT TO authenticated WITH CHECK (is_whitelisted());

CREATE POLICY "Whitelisted users can update movements" 
ON movements FOR UPDATE TO authenticated USING (is_whitelisted()) WITH CHECK (is_whitelisted());

CREATE POLICY "Whitelisted users can delete movements" 
ON movements FOR DELETE TO authenticated USING (is_whitelisted());

-- ============================================================================
-- 6. INITIAL DATA SEEDING
-- Replace the email below with your email address to whitelist yourself immediately.
-- Run this statement to unlock the application for your account.
-- ============================================================================
INSERT INTO allowed_users (email, is_admin) VALUES ('massimonodin@gmail.com', true);
INSERT INTO allowed_users (email, is_admin) VALUES ('adriancathy1@gmail.com', true);
